FROM golang:1.24 AS builder

WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o main .

# Küçük final image
FROM gcr.io/distroless/base-debian12
WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 3001
CMD ["./main"]
# CMD ["air", "-c", ".air.toml"]